version: '2'
services:
    openhab2:
      image: "openhab/openhab:2.1.0-armhf"
      container_name: openhab2
      restart: always
      # user: `id openhab`
      devices:
        - /dev/ttyACM0
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/etc/timezone:/etc/timezone:ro"
        - "/opt/openhab/addons:/openhab/addons"
        - "/opt/openhab/conf:/openhab/conf"
        - "/opt/openhab/userdata:/openhab/userdata"
        - "/opt/openhab/raspberry-remote:/home/pi/raspberry-remote"
      ports:
        - "8080:8080"
      depends_on:
        - homegear
        - influxdb
      links:
        - homegear
        - influxdb
      environment:
        OPENHAB_HTTP_PORT: "8080"
        OPENHAB_HTTPS_PORT: "8443"

    homegear:
      image: "homegear/rpi-homegear:stable"
      container_name: homegear
      restart: always
      devices:
        - /dev/ttyACM0
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
        - "/etc/timezone:/etc/timezone:ro"
        - "/opt/homegear/etc:/etc/homegear"
        - "/opt/homegear/lib:/var/lib/homegear"
        - "/opt/homegear/log:/var/log/homegear"
      ports:
        - "2001:2001"
        - "2002:2002"
        - "2003:2003"

    influxdb:
      image: "hypriot/rpi-influxdb"
      container_name: "influxdb"
      restart: always
      ports:
        - "8086:8086"
      volumes:
        - "/opt/influxdb/data:/data"
      environment:
        ADMIN_USER: openhab2
        INFLUXDB_INIT_PWD: habopen
        PRE_CREATE_DB: openhab
